### PR TITLE
add support for ash 3

### PR DESCRIPTION
**Pull request by jsw800**
Hey, love the little helper library 🙂 I wanted to pull it into a brand new project I'm working on in Ash 3 (which is technically still in the RC stage). Since the library currently only supports ash 2 it needed some changes to support this.

Not sure how you handle gitops/publishing releases/etc. so please let me know if there's anything here I need to change - this would be a breaking change and this new version would _not_ work for ash 2, so if this is not something you want to support yet without a more in-depth strategy to support both, feel free to close this too.

### CODE REVIEW

**Comment by jsw800** [comment]
The relevant breaking changes in Ash 3 ended up being

- `private?` was changed and inverted to use `public?` instead
- `Ash.NotSelected` was collapsed into `Ash.NotLoaded`
- the Spark DSL seems to have changed and was unhappy with the type specification you were doing on the `customize` option - I'm not sure if this is because Spark removed support for that style of type specification, or if it never actually supported it in the first place and only added the validation step in this major release.

**Comment by jsw800** [comment]
@vonagam I don't seem to be able to add you as a reviewer, so just gonna tag you for visibility here ^

**Comment by vonagam** [comment]
Really cool. 

I was planning to add support for Ash 3 once it is released, which should happen in around 2 weeks.

I need to investigate Spark thing, it might be a bug on their side. At least in some places it still shows support for such specification, for example [here](https://github.com/ash-project/spark/blob/0d74d595b8a06d71e1182199ed2167bdcbd14b6d/lib/spark/options/docs.ex#L289). So, with old spec the tests fail or how can I reproduce the verification error?

Do you need to have `ash_jason` released or can you wait and use your branch in meantime (with `git` or `path`)? I prefer to wait if possible and then merge this PR after official release, but if you have a setup that needs an official release of `ash_jason` I can do it too, not a problem.

**Comment by jsw800** [comment]
> I need to investigate Spark thing, it might be a bug on their side. At least in some places it still shows support for such specification

Yeah, I'm really not sure what's up here - this is my first foray into spark so I'm not an expert on it at all. I didn't investigate that super deeply, but based on that function in their code it does look like it should be supported, so that does smell like a bug on their end.

I'll look into using a git ref for now, it does make sense to me to wait for the full ash 3 release before publishing this. I can update the version in mix.exs when that happens to point to the official released version.

**Comment by vonagam** [comment]
Ok. So we'll wait for the release. In meantime I'll look into that Spark issue.

**Comment by vonagam** [comment]
Ok, for record, fixed the spark issue on Github (but who knows when will be the next Spark release).

**Comment by jsw800** [comment]
@vonagam I added a change here which fixes a dialyzer issue I was having when using this in a project. Basically, when no merge/customize options are provided, dialyzer knows those `@merge` and `@customize` attributes are nil at compile time, so it gets angry about trying to use them in `Map.merge`/calling the `nil` customize function (even though they'll never be called, but since it's only a runtime check that prevents this, dialyzer still gets mad).

**Comment by vonagam** [comment]
Ash 3 is released. So I've asked for new release of Spark.

Will merge this and release new version by Sunday.

**Comment by vonagam** [comment]
Ok, I've merged and did some small clean up. Also renamed `AshJason.Extension` -> `AshJason.Resource` to align with official extensions.

Let me know if it works for you and if so I'll publish the release.

**Comment by jsw800** [comment]
@vonagam looks great to me!

**Comment by vonagam** [comment]
Published.

**Pull request merged**
